name: cpp-linter

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-linter.yml'
      - 'cpp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/cpp-linter.yml'
      - 'cpp/**'

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '14'
          check-path: 'cpp'

      - name: Run BUILD file style check.
        uses: thompsonja/bazel-buildifier@v0.4.0
