name: Go-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - 'cpp/**'
      - 'go/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - 'cpp/**'
      - 'go/**'

jobs:

  build:
    runs-on: macos-latest
    env:
      TEST_TMPDIR: "/Users/runner/.cache/bazel"
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
       path: "/Users/runner/.cache/bazel"
       key: bazel-go-osx

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build C++ library for Go
      working-directory: ./go/lib
      run: ./build_libcarmen.sh

    - name: Build Go
      working-directory: ./go
      run: go build -v ./...

    - name: Run Go tests
      working-directory: ./go
      run: go test -v ./...
